{% set name = "rstr" %}
{% set version = "3.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 54b36313a3aecb37450083004f3951cbf04687eeadb1ede90e8bf48fcbabd736

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - rstr
    - rstr.tests

about:
  home: http://bitbucket.org/leapfrogdevelopment/rstr/overview
  license: BSD
  license_family: BSD
  license_file: LICENSE.txt
  summary: Generate random strings in Python
  doc_url: http://bitbucket.org/leapfrogdevelopment/rstr/overview
  dev_url: http://bitbucket.org/leapfrogdevelopment/rstr/overview

extra:
  recipe-maintainers:
    - claymcleod
